### ISSUE TITLE
`?`

### ISSUE THREAD

**Issue by emgee3** [dthree/wat#22]
Typing a single question mark (`?`), while not necessarily idiomatic, is sometimes used in command line tools to display help. In `wat`, it's implemented as a quick way to throw an error and return to the shell. This design decision might best be reviewed. Error message follows:

```
$ wat
? ?
readline.js:924
            throw err;
            ^

SyntaxError: Invalid regular expression: /(?)/: Invalid group
    at new RegExp (native)
    at forEachInIndex.filter.okay (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/clerk/clerk.js:164:19)
    at traverse (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/clerk/clerk.js:138:17)
    at traverse (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/clerk/clerk.js:143:13)
    at traverse (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/clerk/clerk.js:143:13)
    at Object.forEachInIndex (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/clerk/clerk.js:148:5)
    at Object.search (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/clerk/clerk.js:154:10)
    at CommandInstance.<anonymous> (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/dist/vorpal/catch.js:153:33)
    at EventEmitter.session.execCommandSet (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/node_modules/vorpal/lib/session.js:432:24)
    at EventEmitter.vorpal._exec (/Users/mg/.nvm/versions/node/v4.1.2/lib/node_modules/wat/node_modules/vorpal/lib/vorpal.js:798:18)
```

**Comment by dthree** [comment]
I thought it was fairly graceful.

**Comment by dthree** [comment]
Fixed.
