### ISSUE TITLE
GitHub search dies horribly with `ReferenceError: attacher is not defined`

### ISSUE THREAD

**Issue by iankronquist** [dthree/wat#25]
```
 wat 
? github testing123
 
/Users/Ian/gg/timesync-node/node_modules/wat/dist/spider/github.js:36
            var md = mdast().use(stripBadges).use(attacher);
                                                  ^

ReferenceError: attacher is not defined
    at /Users/Ian/gg/timesync-node/node_modules/wat/dist/spider/github.js:36:51
    at Request._callback (/Users/Ian/gg/timesync-node/node_modules/wat/dist/util.js:542:11)
    at Request.self.callback (/Users/Ian/gg/timesync-node/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/Ian/gg/timesync-node/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/Ian/gg/timesync-node/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)

```

**Comment by dthree** [comment]
Yeah - haven't gotten back to that part yet (that's why I had left it off the tour for now). Should be up in a day or two.

**Comment by dthree** [comment]
Fixed :)

**Comment by iankronquist** [comment]
Thanks!

**Comment by dthree** [comment]
No probs. Any other feedback / ideas are welcome, btw. Would like to release wat in the next few weeks.
