### ISSUE TITLE
Cant build local version - problem with 'initClerk'

### ISSUE THREAD

**Issue by defel** [dthree/wat#29]
Hi, 

I forked the project and tried to build it local: 

```bash
npm install
gulp all
```

and get the following error: 

```
[18:20:21] Using gulpfile ~/code/playground/wat/gulpfile.js
[18:20:21] Starting 'initClerk'...
[18:20:21] 'initClerk' errored after 135 ms
[18:20:21] TypeError: undefined is not a function
    at Gulp.<anonymous> (/home/alexander.weiher/code/playground/wat/gulpfile.js:21:9)
    at module.exports (/home/alexander.weiher/code/playground/wat/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/alexander.weiher/code/playground/wat/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/alexander.weiher/code/playground/wat/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/alexander.weiher/code/playground/wat/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /home/alexander.weiher/code/playground/wat/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

The problem is in the gulp-task 'initClerk' - the start function does not exist: 

```js
gulp.task('initClerk', function(){
  clerk = require('./dist/clerk/clerk');
  clerk.start({
    updateRemotely: false
  });
})
```

```
// console.log(clerk);
function (app) {
  clerk.app = app;
  clerk.indexer = require('./indexer')(app);
  clerk.history = require('./history')(app);
  clerk.updater = require('./updater')(app);
  clerk.config = require('./config')(app);
  clerk.autodocs = require('./autodocs')(app);
  clerk.prefs = require('./prefs')(app);
  return clerk;
}
```

Any ideas what I can do?

**Comment by dthree** [comment]
Hey. Whoops - I haven't updated or looked at the docs in a while, and I had been doing a bunch of refactors on the autodocs.

Let me get this working for you as quick as I can.

**Comment by dthree** [comment]
@defel okay man I just worked this over and tested it a bunch, so it should work good now:

1. Make sure you have the latest docs from the repo with a rebase,
2. Instead of `gulp all`, do `gulp index`, and then push. I'll update the docs shortly!

**Comment by defel** [comment]
Perfect, it works! :ok_hand:

**Comment by dthree** [comment]
Great!
