### ISSUE TITLE
Latest version of wat fails

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#9]
Looks like a module was introduced that's causing problems?

This is right after a fresh `npm i -g wat`.

<img width="649" alt="screen shot 2015-08-21 at 12 07 57 pm" src="https://cloud.githubusercontent.com/assets/885648/9415559/6e1ab37e-47fd-11e5-8613-5d9006661071.png">

Textual error:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'unzip'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/qix/.nvm/versions/io.js/v3.1.0/lib/node_modules/wat/lib/clerk.js:10:15)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by dthree** [comment]
Whoops. Time to add those tests.

**Comment by dthree** [comment]
Okay fixed this - can you try again?

Also, try typing `wat js array splice` from your raw command line :fire:

**Comment by Qix-** [comment]
Works - thanks!

**Comment by dthree** [comment]
No probs.

Almost done with ES6 transpiling, so after that it should work on most Node versions.
